services:
  cupdate:
    image: ghcr.io/alexgustafsson/cupdate:0.14.0
    ports:
      - 8080:8080
    environment:
      CUPDATE_CACHE_PATH: /var/run/cachev1.boltdb
      CUPDATE_DB_PATH: /var/run/dbv1.sqlite
      CUPDATE_DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - target: /tmp
        type: tmpfs
