trailingComma: es5
tabWidth: 2
semi: false
singleQuote: true
endOfLine: lf
importOrder:
  - '^[^.]' # 1. Any normal dependency - node libraries etc.
  - '^(\.*)/?' # 2. Any local dependency
importOrderSeparation: true
importOrderSortSpecifiers: true
overrides:
  - files:
      - 'tsconfig.json'
    options:
      parser: 'json'
plugins: ['@trivago/prettier-plugin-sort-imports']
