---
repos:
  - repo: local
    hooks:
      - id: biome
        name: Lint code using Biome
        entry: npx biome ci --no-errors-on-unmatched
        language: system
        types: [text]
      - id: prettier
        name: Lint markdown using Prettier
        entry: npx prettier --check
        language: system
        types: [text]
        files: \.(md|yml|yaml)$
      - id: store
        name: Lint store migrations
        entry: ./tools/ci/lint-store-migrations.sh
        language: system
        types: [text]
        files: internal/store/.*
