apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - rbac.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cupdate
      spec:
        template:
          spec:
            automountServiceAccountToken: true
            serviceAccountName: cupdate
