blank_issues_enabled: true

contact_links:
  - name: Cupdate Community Support
    url: https://github.com/AlexGustafsson/cupdate/discussions
    about: Please ask and answer questions here.

  - name: Cupdate Security Issues
    url: https://github.com/AlexGustafsson/cupdate/security/advisories/new
    about: Please report security vulnerabilities here.
