name: UI Bug Report
description: File a bug report for the UI.
title: "UI Bug: "
labels: ["bug", "ui"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report!
        Testing Cupdate, finding and filing bugs is a great way to contribute.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: >
        What happened? What did you expect to happen?
        If applicable, please include screenshots.
    validations:
      required: true
  - type: textarea
    id: cupdate-version
    attributes:
      label: What version of Cupdate are you using?
      placeholder: v0.22.2
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: dropdown
    id: os
    attributes:
      label: What OS(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Linux
        - Android
        - macOS
        - iOS
        - iPadOS
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
        Please copy and paste any relevant log output from the browser's dev
        tools. This will be automatically formatted into code, so no need for
        backticks.
      render: text
