apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: cupdate-config
    literals:
      - CUPDATE_API_ADDRESS=0.0.0.0
      - CUPDATE_CACHE_PATH=/var/run/data/cachev1.boltdb
      - CUPDATE_DB_PATH=/var/run/data/dbv1.sqlite

resources:
  - deployment.yaml
  - service.yaml
