apiVersion: v1
kind: Service
metadata:
  name: cupdate
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8080
  selector:
    app: cupdate
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cupdate
  labels:
    app: cupdate
spec:
  selector:
    matchLabels:
      app: cupdate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cupdate
    spec:
      automountServiceAccountToken: true
      serviceAccountName: cupdate
      containers:
        - name: cupdate
          image: ghcr.io/alexgustafsson/cupdate
          env:
            - name: CUPDATE_CACHE_PATH
              value: /run/data/cachev1.boltdb
            - name: CUPDATE_DB_PATH
              value: /run/data/dbv1.sqlite
            - name: CUPDATE_API_ADDRESS
              value: "0.0.0.0"
          volumeMounts:
            - name: data
              mountPath: /run/data
          ports:
            - name: web
              containerPort: 8080
          resources:
            requests:
              cpu: "0.01"
              memory: "64Mi"
            limits:
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 50Mi
