{
 "title": "Cupdate",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Loki", "query": "loki" },
   { "name": "Prometheus", "query": "prometheus" },
   { "name": "Tempo", "query": "tempo" }
  ]
 },
 "panels": [
  {
   "title": "Processing images",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cupdate_worker_processing_images",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available worker burst",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cupdate_worker_available_burst", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average worker duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cupdate_worker_processed_images_duration_seconds / cupdate_worker_processed_images_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP codes",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cupdate_http_requests_total) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cupdate_http_cache_hits_total / sum(cupdate_http_requests_total)",
     "legendFormat": "Hit"
    },
    {
     "expr": "1 - cupdate_http_cache_hits_total / sum(cupdate_http_requests_total)",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Cache entries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cupdate_cache_entries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "p95" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"cupdate\"}[$__rate_interval]))",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "p95" ] } },
   "targets": [
    {
     "expr": "avg(go_memstats_alloc_bytes{job=\"cupdate\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(cupdate_http_requests_total[$__rate_interval])) by (hostname, code) != 0",
     "legendFormat": "{{code}} {{hostname}}"
    },
    {
     "expr": "increase(cupdate_worker_processed_images_total[$__rate_interval]) != 0",
     "legendFormat": "Processed images"
    },
    {
     "expr": "increase(cupdate_cache_entries[$__rate_interval]) != 0",
     "legendFormat": "Cached requests"
    }
   ]
  },
  {
   "title": "HTTP origins",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cupdate_http_requests_total) by (hostname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"cupdate\"} | label_format level=detected_level | level != `debug`"
    }
   ]
  },
  {
   "title": "Job runs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "filters": [
      { "id": "8edae1df", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "cupdate" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "cupdate.workflow.step.run" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"cupdate\" && name=\"cupdate.workflow.job.run\"} | count_over_time() by (span.cupdate.workflow.job.name)",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Step durations (95th)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "filters": [
      { "id": "8edae1df", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "cupdate" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "cupdate.workflow.step.run" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"cupdate\" && name=\"cupdate.workflow.step.run\"} | by(span.cupdate.workflow.step.name)",
     "tableType": "spans"
    }
   ]
  }
 ]
}