name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - cmd/**
      - internal/**
      - go.*
      - web/**
      - .yarn
      - .yarnrc.yml
      - biome.jsonc
      - package.json
      - tailwind.config.js
      - tsconfig.json
      - vite.config.ts
      - yarn.lock
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - cmd/**
      - internal/**
      - go.*
      - web/**
      - .yarn
      - .yarnrc.yml
      - biome.jsonc
      - package.json
      - tailwind.config.js
      - tsconfig.json
      - vite.config.ts
      - yarn.lock

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run go tests
        run: go test -short -v ./...

      - name: Run web tests
        run: yarn run test

  build-web:
    name: Build web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build web
        run: yarn build

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: internal/web/public

  build-cupdate:
    name: Build cupdate
    runs-on: ubuntu-latest
    needs: build-web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download web build
        uses: actions/download-artifact@v4
        with:
          name: web
          path: internal/web/public

      - name: Build cupdate
        run: go build -o cupdate cmd/cupdate/*.go
