name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - cmd/**
      - internal/**
      - go.*
      - web/**
      - .yarn
      - .yarnrc.yml
      - biome.jsonc
      - package.json
      - tailwind.config.js
      - tsconfig.json
      - vite.config.ts
      - yarn.lock
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - cmd/**
      - internal/**
      - go.*
      - web/**
      - .yarn
      - .yarnrc.yml
      - biome.jsonc
      - package.json
      - tailwind.config.js
      - tsconfig.json
      - vite.config.ts
      - yarn.lock

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn run lint

      - name: Lint store migrations
        run: ./tools/ci/lint-store-migrations.sh

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run go tests
        env:
          # Use the toolchain specified in go.mod, or newer
          GOTOOLCHAIN: auto
        run: go test -race -short -v ./...

      - name: Run web tests
        run: yarn run test

  build-web:
    name: Build web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build web
        run: yarn build

      - name: Upload build output
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: web
          path: internal/web/public

  build-cupdate:
    name: Build cupdate
    runs-on: ubuntu-latest
    needs: build-web

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download web build
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: web
          path: internal/web/public

      - name: Build cupdate
        env:
          # Use the toolchain specified in go.mod, or newer
          GOTOOLCHAIN: auto
        run: go build -o cupdate cmd/cupdate/*.go
