name: Build Docker image

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - .github/workflows/docker.yaml
      - .dockerignore
      - Dockerfile
      - cmd/**
      - internal/**
      - go.*
      - web/**
      - .yarn
      - .yarnrc.yml
      - biome.jsonc
      - package.json
      - tsconfig.json
      - vite.config.ts
      - yarn.lock

permissions:
  contents: read

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Publish OCI image

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # We need the entire history to determine the current version
          fetch-depth: 0

      - name: Log in to the container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Determine tag
        id: determine_tag
        run: |
          TAG="${{ (github.ref_type == 'tag' && github.ref_name) || 'latest' }}"
          echo "tag=${TAG#v}" >> "$GITHUB_OUTPUT"
          echo -n "revision=" >> "$GITHUB_OUTPUT"
          git describe >> "$GITHUB_OUTPUT"
          echo -n "date=" >> "$GITHUB_OUTPUT"
          date --iso-8601=seconds >> "$GITHUB_OUTPUT"

      - name: Build and publish
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        id: push
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/alexgustafsson/cupdate:${{ steps.determine_tag.outputs.tag }}
          build-args: |
            CUPDATE_VERSION=${{ steps.determine_tag.outputs.revision }}
          labels: |
            org.opencontainers.image.title=Cupdate
            org.opencontainers.image.description=Cupdate keeps track of image updates.
            org.opencontainers.image.source=https://github.com/AlexGustafsson/cupdate
            org.opencontainers.image.version=${{ steps.determine_tag.outputs.tag }}
            org.opencontainers.image.revision=${{ steps.determine_tag.outputs.revision }}
            org.opencontainers.image.created=${{ steps.determine_tag.outputs.date }}
            org.opencontainers.image.licenses=MIT

      - name: Attest
        uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 #v2.2.3
        with:
          subject-name: ghcr.io/alexgustafsson/cupdate
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
