name: Build Docker image

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - .github/workflows/docker.yaml
      - .dockerignore
      - Dockerfile
      - cmd/**
      - internal/**
      - go.*
      - web/**
      - .yarn
      - .yarnrc.yml
      - biome.jsonc
      - package.json
      - tailwind.config.js
      - tsconfig.json
      - vite.config.ts
      - yarn.lock

permissions:
  contents: read

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Publish OCI image

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # We need the entire history to determine the current version
          fetch-depth: 0

      - name: Log in to the container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3.4.0

      - name: Determine tag
        id: determine_tag
        run: |
          TAG="${{ (github.ref_type == 'tag' && github.ref_name) || 'latest' }}"
          echo "tag=${TAG#v}" >> "$GITHUB_OUTPUT"
          echo -n "revision=" >> "$GITHUB_OUTPUT"
          git describe >> "$GITHUB_OUTPUT"
          echo -n "date=" >> "$GITHUB_OUTPUT"
          date --iso-8601=seconds >> "$GITHUB_OUTPUT"

      - name: Build and publish
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6.14.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/alexgustafsson/cupdate:${{ steps.determine_tag.outputs.tag }}
          build-args: |
            CUPDATE_VERSION=${{ steps.determine_tag.outputs.revision }}
          labels: |
            org.opencontainers.image.title=Cupdate
            org.opencontainers.image.description=Cupdate keeps track of image updates.
            org.opencontainers.image.source=https://github.com/AlexGustafsson/cupdate
            org.opencontainers.image.version=${{ steps.determine_tag.outputs.tag }}
            org.opencontainers.image.revision=${{ steps.determine_tag.outputs.revision }}
            org.opencontainers.image.created=${{ steps.determine_tag.outputs.date }}
            org.opencontainers.image.licenses=MIT
