name: GitHub Actions Security Analysis

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/zizmor.yaml
      - .github/workflows/**/*.yaml
      - .github/actions/**/*.yaml
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/zizmor.yaml
      - .github/workflows/**/*.yaml
      - .github/actions/**/*.yaml
  schedule:
    # Some random-ish cron to help with GitHub Actions scheduling, once a week
    - cron: 29 11 * * 2

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Write events
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          persona: pedantic
          version: v1.16.0
